services:
  backend:
    container_name: backend
    image: ghcr.io/screama6/film-react-nest/backend:latest
    depends_on:
      - postgres
    networks:
      - webnet
    environment:
      - DATABASE_DRIVER=postgres
      - DATABASE_URL=postgres://student:student@postgres:5432/student
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: ghcr.io/screama6/film-react-nest/frontend:latest
    networks:
      - webnet
    volumes:
      - frontend_dist:/app/dist
    environment:
      - VITE_API_URL=https://athdevtvs.students.nomorepartiesco.ru/api/afisha
      - VITE_CDN_URL=https://athdevtvs.students.nomorepartiesco.ru/content/afisha

  postgres:
    container_name: postgrescv
    image: postgres:14.8-alpine3.18
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/database-init.sql
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - webnet
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student

  pgadmin:
    image: dpage/pgadmin4:7.2
    container_name: pgadmin
    env_file:
      - backend/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
    networks:
      - webnet
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - webnet
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/var/www/frontend:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro

  certbot:
    image: certbot/certbot:latest
    networks:
      - webnet
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres-data:
  pgadmin-data:
  frontend_dist:

networks:
  webnet:
